### ISSUE TITLE
[question] what's the point of this repo vs ofxImGui?

### ISSUE THREAD

**Issue by moebiussurfing** [PlaymodesStudio/ofxImGuiSimple#1]
hey @eduardfrigola ,
what's the difference with the more "popular" repo?

One of the problems I had, it was that I can not use more than one ImGui instance without problems. 
I have seen some ofxImGui branch that handles multiple contexts and works fine.
I am looking for a recent branch to use. 
Any idea?

I have seen this other too: 
https://github.com/pjulien21/ofImGuiApp

**Comment by eduardfrigola** [comment]
Yes it is similar to Juliens aproach, but even simpler.
The reason for not using ofxImGui is that uses custom backend implementation that is not straightforward to mantain, and **mainly, to add docking / multiview functionality.**
This addon it is simply a wrapper for imgui_impl_glfw and imgui_impl_opengl2/3 similar of what is done in imgui example.

I have no idea with multiple context, as I am using the viewports that imgui generates for a multiwindow gui application.

And it is called simple because it does not handle a lot of of stuff, so you have to use pure imgui between ImGui::Begin() and ImGui::End() as this window could be outside OF window, and therefore not catching mouse or key events.

**Comment by moebiussurfing** [comment]
it worked nicely on Windows. Thanks.
I like because the GUI panel goes to a floating window apart from the main window (like ofxImGui does).

--

If you don't mind...Sorry to ask, but I am deciding what way to choose...

How would be your workflow if you have many classes/addons with parameters that you want to control on the GUI?
That's why I ask about contexts... One solution could be to expose your class params as 'public:',
and to create a subWindow/dock/tab into your ofApp main (and only) ImGui instance.

Another way could be to create and ImGui instance in every class/addon, but I think they can collide.

(I should check your code in ofxOcenode to see how you used ImGui. Also because I want to make very basic matrix patching to connect some inputs/outputs matrix)

**Comment by eduardfrigola** [comment]
Hi @moebiussurfing Thanks for testing it with Windows.

Depending on the type of controls that you want an approach similar to ofxOceanode might help. You can have a class that gets ofParameterGroup and creates a gui component for each parameter. Another option would be to create the gui for every class. (You could use the helpers in ofxImGui). You only need to call the funcion that call the imgui code inside your class between gui.begin() and gui.end() (as in the example).

**Comment by eduardfrigola** [comment]
Hi @moebiussurfing Thanks for testing it with Windows.

Depending on the type of controls that you want an approach similar to ofxOceanode might help. You can have a class that gets ofParameterGroup and creates a gui component for each parameter. Another option would be to create the gui for every class. (You could use the helpers in ofxImGui). You only need to call the funcion that call the imgui code inside your class between gui.begin() and gui.end() (as in the example).
